title: Gabriel Centeno
logo: /assets/img/profile.jpg
description: Aspiring Software Engineer and Creative. Interested in Video Game Development, Graphics and Animation.

#show_downloads: false
theme: jekyll-theme-minimal
